server.port: 8084

spring:
  application.name: core-service
  datasource:
    url: jdbc:mysql://localhost/sc_core_service
    username: sc_user
    password: sc_password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl.defaultZone: http://localhost:8082/eureka/
