server.port: 8083

spring:
  application.name: user-service
  datasource:
    url: jdbc:postgresql://localhost/sc_user_service
    username: sc_user
    password: sc_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  liquibase:
    enabled: false

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl.defaultZone: http://localhost:8082/eureka/
